### ISSUE TITLE
Session 1 - Logic - HR Challenge

### ISSUE THREAD

**Issue by fcu423** [dsmith-projects/net-bootcamp#1]
Hola David!

Algunas cosas que pueden hacer tu código un poco mejor:

- En el de la suma de la diagonal podías haber usado Math.Abs en el resultado para evitarte la validación y la multiplicación por -1
- En el de grading - El cálculo del múltiplo más cercano se puede optimizar mucho. Pero dejando la lógica como la hiciste podrías corregir que: empezar en 1 no está del todo bien pues 1 no es múltiplo de 5, hacer la primera multiplicación 0 no añade valor a la solución pues esta multiplicación siempre va a dar cero, así que i debería arrancar en otro valor más óptimo.
- En el de grading - Es mejor si haces los cambios sobre el mismo vector, con esto ahorrarás memoria y el código será mucho más simple. Manejando una sola lista inclusive podrías eliminar la validación de `grades[i] < 38` y simplemente hacer la lógica para `grades[i] >= 38`

Me gustó mucho el for que usaste en la diagonal y la solución del de marte, muy buen trabajo.

Corregí lo de arriba! 👍

**Comment by dsmith-projects** [comment]
Gracias, por los comentarios. Trabajaré en las correcciones.

**Comment by dsmith-projects** [comment]
Hola @fcu423, ya he hecho las correcciones. Para ello hice un branch nuevo llamado 'correciones-session1' (escribí mal 'correcciones').
En cuanto puedas, me dices cómo lo ves y si corregí todo bien. 

¡Gracias!

**Comment by fcu423** [comment]
Resuelto!
